version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: flaviogf
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: The first app
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
